{{ $pattern := "" -}}
{{ if eq .chezmoi.os "darwin" -}}
  {{ $pattern := "aarch64-apple-darwin" -}}
{{ else if eq .chezmoi.os "linux" -}}
  {{ if eq .chezmoi.arch "arm64" -}}
    {{ $pattern := "aarch64-unknown-linux-musl" -}}
  {{ else if eq .chezmoi.arch "amd64" -}}
    {{ $pattern := "x86_64-unknown-linux-musl" -}}
  {{ end -}}
{{ end -}}

[".local/share/man/man1/git-cliff.1"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "orhun/git-cliff" (printf "*%s*" $pattern) }}'
stripComponents = 1
path = "man/git-cliff.1"

[".config/zsh/completions/_git-cliff.sh"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "orhun/git-cliff" (printf "*%s*" $pattern) }}'
stripComponents = 1
path = "completions/_git-cliff"

[".config/bash/completions/_git-cliff.sh"]
type = "archive-file"
url = '{{ gitHubLatestReleaseAssetURL "orhun/git-cliff" (printf "*%s*" $pattern) }}'
stripComponents = 1
path = "completions/git-cliff.bash"
