{{ range $name, $opts := .zshPlugins.gitRepos -}}
[".config/zsh/plugins/{{ $name }}"]
type = "git-repo"
url = "{{ $opts.repoUrl }}"
clone.args = ["--depth", "1", "--branch", "{{ $opts.ref }}"]
{{ end -}}

{{ range $name, $opts := .zshPlugins.files -}}
[".config/zsh/plugins/{{ $name }}"]
type = "file"
url = "{{ $opts.repoUrl }}"
{{ end -}}
